import * as fs from "fs";
import * as path from "path";
import { parseCargoLock } from "../../../../lib/analyzer/applications/rust/cargo-lock-parser";
import { cargoFilesToScannedProjects } from "../../../../lib/analyzer/applications/rust/cargo";

const fixturesPath = path.join(__dirname, "../../../fixtures/rust");

function loadFixture(subdir: string): string {
  return fs.readFileSync(
    path.join(fixturesPath, subdir, "Cargo.lock"),
    "utf-8",
  );
}

function countFixturePackagesInGraph(
  depGraph: { getPkgs(): { name: string; version: string }[] },
  fixtureContent: string,
): void {
  const lock = parseCargoLock(fixtureContent);
  for (const pkg of lock.packages) {
    const matches = depGraph
      .getPkgs()
      .filter((p) => p.name === pkg.name && p.version === pkg.version);
    expect(matches).toHaveLength(1);
  }
}

describe("cargoFilesToScannedProjects", () => {
  describe("v3 fixture", () => {
    const filePath = "/app/Cargo.lock";
    let results: Awaited<ReturnType<typeof cargoFilesToScannedProjects>>;

    beforeAll(async () => {
      results = await cargoFilesToScannedProjects({
        [filePath]: loadFixture("v3"),
      });
    });

    it("returns one scan result for Cargo.lock", () => {
      expect(results).toHaveLength(1);
      expect(results[0].identity.type).toBe("cargo");
      expect(results[0].identity.targetFile).toBe(filePath);
    });

    it("includes testedFiles fact with the lockfile basename", () => {
      const testedFilesFact = results[0].facts.find(
        (f) => f.type === "testedFiles",
      );
      expect(testedFilesFact).toBeDefined();
      expect(testedFilesFact!.data).toEqual(["Cargo.lock"]);
    });

    it("builds a cargo dep graph rooted at the synthetic app package", () => {
      const depGraphFact = results[0].facts.find((f) => f.type === "depGraph");
      expect(depGraphFact).toBeDefined();

      const depGraph = depGraphFact!.data;
      expect(depGraph.pkgManager.name).toBe("cargo");
      expect(depGraph.rootPkg.name).toBe("app");
      expect(depGraph.rootPkg.version).toBe("0.0.0");
    });

    it("includes every fixture crate exactly once in the graph", () => {
      const depGraph = results[0].facts.find(
        (f) => f.type === "depGraph",
      )!.data;
      countFixturePackagesInGraph(depGraph, loadFixture("v3"));
    });

    it("places depth-2 crates under their parent rather than the root", () => {
      const depGraph = results[0].facts.find(
        (f) => f.type === "depGraph",
      )!.data;
      expect(depGraph.isTransitive({ name: "serde", version: "1.0.193" })).toBe(
        true,
      );
      expect(
        depGraph.directDepsLeadingTo({ name: "serde", version: "1.0.193" }),
      ).toEqual([{ name: "serde_derive", version: "1.0.193" }]);
    });
  });

  describe("duplicate-versions fixture", () => {
    it("produces two distinct rand nodes", async () => {
      const results = await cargoFilesToScannedProjects({
        "/app/Cargo.lock": loadFixture("duplicate-versions"),
      });
      expect(results).toHaveLength(1);

      const depGraph = results[0].facts.find(
        (f) => f.type === "depGraph",
      )!.data;
      const randPkgs = depGraph.getPkgs().filter((pkg) => pkg.name === "rand");
      expect(randPkgs).toHaveLength(2);
      expect(randPkgs.map((pkg) => pkg.version).sort()).toEqual([
        "0.7.3",
        "0.8.5",
      ]);
    });
  });

  describe("workspace fixture", () => {
    it("returns one result containing every crate from the lockfile", async () => {
      const content = loadFixture("workspace");
      const results = await cargoFilesToScannedProjects({
        "/app/Cargo.lock": content,
      });
      expect(results).toHaveLength(1);
      countFixturePackagesInGraph(
        results[0].facts.find((f) => f.type === "depGraph")!.data,
        content,
      );
    });
  });

  describe("no-local-package fixture", () => {
    it("returns one result containing every crate from the lockfile", async () => {
      const content = loadFixture("no-local-package");
      const results = await cargoFilesToScannedProjects({
        "/app/Cargo.lock": content,
      });
      expect(results).toHaveLength(1);
      countFixturePackagesInGraph(
        results[0].facts.find((f) => f.type === "depGraph")!.data,
        content,
      );
    });
  });

  describe("dependency cycle", () => {
    it("terminates without throwing", async () => {
      const cyclicLock = `# This file is automatically @generated by Cargo.
[[package]]
name = "crate-a"
version = "1.0.0"
dependencies = [
 "crate-b",
]

[[package]]
name = "crate-b"
version = "1.0.0"
dependencies = [
 "crate-a",
]
`;

      await expect(
        cargoFilesToScannedProjects({
          "/app/Cargo.lock": cyclicLock,
        }),
      ).resolves.toHaveLength(1);
    });
  });

  describe("invalid or non-lock inputs", () => {
    it("returns zero results for malformed Cargo.lock", async () => {
      await expect(
        cargoFilesToScannedProjects({
          "/app/Cargo.lock": loadFixture("malformed"),
        }),
      ).resolves.toEqual([]);
    });

    it("returns zero results for empty input", async () => {
      await expect(cargoFilesToScannedProjects({})).resolves.toEqual([]);
    });

    it("returns zero results for non-Cargo.lock files", async () => {
      await expect(
        cargoFilesToScannedProjects({
          "/app/Cargo.toml": "[package]",
        }),
      ).resolves.toEqual([]);
    });
  });
});
