import { DepGraph, DepGraphBuilder } from "@snyk/dep-graph";
import * as Debug from "debug";
import { eventLoopSpinner } from "event-loop-spinner";
import * as path from "path";
import { getErrorMessage } from "../../error-utils";
import { DepGraphFact, TestedFilesFact } from "../../facts";
import { AppDepsScanResultWithoutTarget, FilePathToContent } from "./types";

const debug = Debug("snyk");

const PACKAGE_MANAGER_NAME = "cargo";

/**
 * A single `[[package]]` entry parsed out of a Cargo.lock file.
 */
export interface CargoLockPackage {
  name: string;
  version: string;
  // Absent only for the workspace's own member crate(s); present (e.g.
  // "registry+https://github.com/rust-lang/crates.io-index" or a git URL)
  // for every external dependency. This is the signal we use to tell local
  // packages apart from resolved external ones.
  source?: string;
  // Raw dependency references, each either "name" or "name version" (the
  // latter form is only emitted by cargo when the lock file contains more
  // than one version of that crate name).
  dependencies: string[];
}

// NOTE: This is intentionally *not* a general-purpose TOML parser. Cargo.lock
// is machine-generated by `cargo` and has a small, very regular, well-known
// shape (a top-level `version` key, plus a flat list of repeated
// `[[package]]` tables with a fixed set of scalar/array fields -- no nested
// tables, no inline tables, no multi-line strings). Writing a parser
// purpose-built for that shape is enough, is easy to review in full, and
// avoids pulling in a general TOML implementation (or an external
// Rust-lockfile-parser dependency) as extra attack surface for a single,
// narrow use case.
export function parseCargoLock(content: string): CargoLockPackage[] {
  const packages: CargoLockPackage[] = [];

  // Split on the start of each [[package]] table. The first chunk (before
  // the first [[package]]) is the file header (comments + `version = N`)
  // and is discarded here -- callers that need the lockfile format version
  // can read it separately if that's ever needed.
  const blocks = content.split(/\n(?=\[\[package\]\])/);

  for (const block of blocks) {
    if (!block.trimStart().startsWith("[[package]]")) {
      continue;
    }

    const name = matchScalarField(block, "name");
    const version = matchScalarField(block, "version");
    if (!name || !version) {
      // Malformed/unrecognized block (e.g. missing required fields) --
      // skip it defensively rather than failing the whole file.
      debug(`Skipping Cargo.lock [[package]] block missing name/version`);
      continue;
    }

    const source = matchScalarField(block, "source");
    const dependencies = matchDependenciesArray(block);

    packages.push({ name, version, source, dependencies });
  }

  return packages;
}

function matchScalarField(block: string, field: string): string | undefined {
  const match = block.match(new RegExp(`^${field}\\s*=\\s*"([^"]*)"`, "m"));
  return match ? match[1] : undefined;
}

function matchDependenciesArray(block: string): string[] {
  const match = block.match(/^dependencies\s*=\s*\[([\s\S]*?)\]/m);
  if (!match) {
    return [];
  }
  const entries: string[] = [];
  const entryPattern = /"([^"]*)"/g;
  let entryMatch: RegExpExecArray | null;
  while ((entryMatch = entryPattern.exec(match[1])) !== null) {
    entries.push(entryMatch[1]);
  }
  return entries;
}

type PackageLookup = {
  byNameVersion: Map<string, CargoLockPackage>;
  byName: Map<string, CargoLockPackage[]>;
};

function buildLookup(packages: CargoLockPackage[]): PackageLookup {
  const byNameVersion = new Map<string, CargoLockPackage>();
  const byName = new Map<string, CargoLockPackage[]>();

  for (const pkg of packages) {
    byNameVersion.set(`${pkg.name}@${pkg.version}`, pkg);
    const existing = byName.get(pkg.name);
    if (existing) {
      existing.push(pkg);
    } else {
      byName.set(pkg.name, [pkg]);
    }
  }

  return { byNameVersion, byName };
}

// Resolves a raw dependency reference ("name" or "name version") to a
// concrete package. Returns undefined -- and lets the caller debug-log --
// when the reference can't be resolved unambiguously, rather than throwing.
function resolveDependency(
  depRef: string,
  lookup: PackageLookup,
): CargoLockPackage | undefined {
  const spaceIndex = depRef.indexOf(" ");
  if (spaceIndex === -1) {
    const candidates = lookup.byName.get(depRef);
    if (!candidates || candidates.length === 0) {
      return undefined;
    }
    if (candidates.length > 1) {
      // Ambiguous: multiple versions of this crate exist in the lock file
      // but this reference didn't disambiguate with a version suffix.
      return undefined;
    }
    return candidates[0];
  }

  const name = depRef.slice(0, spaceIndex);
  const version = depRef.slice(spaceIndex + 1).trim();
  return lookup.byNameVersion.get(`${name}@${version}`);
}

async function addDependenciesOf(
  parentNodeId: string,
  pkg: CargoLockPackage,
  lookup: PackageLookup,
  visited: Set<string>,
  builder: DepGraphBuilder,
  filePath: string,
): Promise<void> {
  for (const depRef of pkg.dependencies) {
    if (eventLoopSpinner.isStarving()) {
      await eventLoopSpinner.spin();
    }

    const depPkg = resolveDependency(depRef, lookup);
    if (!depPkg) {
      debug(
        `Could not resolve Cargo dependency "${depRef}" of "${pkg.name}@${pkg.version}" in ${filePath}`,
      );
      continue;
    }

    const nodeId = `${depPkg.name}@${depPkg.version}`;
    if (!visited.has(nodeId)) {
      visited.add(nodeId);
      builder.addPkgNode(
        { name: depPkg.name, version: depPkg.version },
        nodeId,
      );
      await addDependenciesOf(
        nodeId,
        depPkg,
        lookup,
        visited,
        builder,
        filePath,
      );
    }
    builder.connectDep(parentNodeId, nodeId);
  }
}

export async function buildDepGraphFromCargoLock(
  lockContent: string,
  lockFilePath: string,
): Promise<DepGraph | null> {
  const packages = parseCargoLock(lockContent);
  if (packages.length === 0) {
    debug(`No parseable [[package]] entries found in ${lockFilePath}`);
    return null;
  }

  const lookup = buildLookup(packages);

  // Cargo omits `source` only for the workspace's own member crate(s) --
  // every resolved external dependency has one. That makes "no source" the
  // signal for "this is (one of) the project's own package(s)".
  const localPackages = packages.filter((pkg) => !pkg.source);

  if (localPackages.length === 0) {
    debug(
      `No local (sourceless) package found in ${lockFilePath}; skipping (unusual/incomplete lock file)`,
    );
    return null;
  }

  const visited = new Set<string>();

  if (localPackages.length === 1) {
    const root = localPackages[0];
    const builder = new DepGraphBuilder(
      { name: PACKAGE_MANAGER_NAME },
      { name: root.name, version: root.version },
    );
    await addDependenciesOf(
      builder.rootNodeId,
      root,
      lookup,
      visited,
      builder,
      lockFilePath,
    );
    return builder.build();
  }

  // More than one sourceless package means this is a Cargo workspace: there
  // isn't a single "the" root package in the lock file itself. As a
  // deliberate simplification (not attempting real workspace-member
  // targeting), synthesize a virtual root that depends directly on every
  // workspace member, named after the lock file's containing directory.
  const virtualRootName =
    path.basename(path.dirname(lockFilePath)) || "cargo-workspace";
  const builder = new DepGraphBuilder(
    { name: PACKAGE_MANAGER_NAME },
    { name: virtualRootName, version: "0.0.0" },
  );

  for (const member of localPackages) {
    const nodeId = `${member.name}@${member.version}`;
    if (!visited.has(nodeId)) {
      visited.add(nodeId);
      builder.addPkgNode(
        { name: member.name, version: member.version },
        nodeId,
      );
      await addDependenciesOf(
        nodeId,
        member,
        lookup,
        visited,
        builder,
        lockFilePath,
      );
    }
    builder.connectDep(builder.rootNodeId, nodeId);
  }

  return builder.build();
}

export async function rustFilesToScannedProjects(
  filePathToContent: FilePathToContent,
): Promise<AppDepsScanResultWithoutTarget[]> {
  const scanResults: AppDepsScanResultWithoutTarget[] = [];

  const lockFilePaths = Object.keys(filePathToContent).filter(
    (filePath) => path.basename(filePath) === "Cargo.lock",
  );

  for (const lockFilePath of lockFilePaths) {
    try {
      const depGraph = await buildDepGraphFromCargoLock(
        filePathToContent[lockFilePath],
        lockFilePath,
      );
      if (!depGraph) {
        continue;
      }

      const depGraphFact: DepGraphFact = {
        type: "depGraph",
        data: depGraph,
      };
      const testedFilesFact: TestedFilesFact = {
        type: "testedFiles",
        data: [path.basename(lockFilePath)],
      };
      scanResults.push({
        facts: [depGraphFact, testedFilesFact],
        identity: {
          type: PACKAGE_MANAGER_NAME,
          targetFile: lockFilePath,
        },
      });
    } catch (err) {
      debug(
        `Failed to parse Cargo.lock at ${lockFilePath}: ${getErrorMessage(
          err,
        )}`,
      );
    }
  }

  return scanResults;
}
