#! /usr/bin/env ts-node

import { createWriteStream } from "fs";
import * as gunzip from "gunzip-maybe";
import * as prettier from "prettier";
import { Readable } from "stream";
import { extract } from "tar-stream";
import { streamToSha256 } from "../lib/stream-utils";

export const DOTNET_RELEASES_METADATA_BASE =
  "https://builds.dotnet.microsoft.com/dotnet/release-metadata";

export const DEFAULT_CHANNELS = ["8.0", "9.0"];

export const DEFAULT_RIDS = ["linux-x64", "linux-arm64", "linux-musl-x64"];

export const KEY_BINARY_NAMES = [
  "libcoreclr.so",
  "System.Private.CoreLib.dll",
] as const;

const KEY_BINARY_NAMES_SET = new Set<string>(KEY_BINARY_NAMES);

export const RUNTIME_TAR_GZ_NAME_PATTERN = /^dotnet-runtime-.*\.tar\.gz$/;

const DOTNET_SHARED_FRAMEWORK_PATH = "shared/Microsoft.NETCore.App/";

export interface DotnetReleaseFile {
  name: string;
  rid: string;
  url: string;
  hash: string;
}

export interface DotnetRelease {
  "release-version": string;
  runtime: {
    version: string;
    files: DotnetReleaseFile[];
  };
}

export interface DotnetReleasesJson {
  "channel-version": string;
  "latest-release": string;
  releases: DotnetRelease[];
}

export interface DownloadPlanEntry {
  version: string;
  rid: string;
  url: string;
}

export interface DotnetSharedFrameworkBinaryInfo {
  version: string;
  binary: string;
  rids: string[];
  sources: string[];
}

export interface PendingDotnetSharedFrameworkHashEntry {
  hash: string;
  version: string;
  binary: string;
  rid: string;
  source: string;
}

export function buildDownloadPlan(
  releasesJson: DotnetReleasesJson,
  requestedVersions: string[],
  requestedRids: string[],
): DownloadPlanEntry[] {
  const versionSet = new Set(requestedVersions);
  const ridSet = new Set(requestedRids);
  const plan: DownloadPlanEntry[] = [];

  for (const release of releasesJson.releases) {
    if (!versionSet.has(release["release-version"])) {
      continue;
    }

    for (const file of release.runtime.files) {
      if (
        !ridSet.has(file.rid) ||
        !RUNTIME_TAR_GZ_NAME_PATTERN.test(file.name)
      ) {
        continue;
      }

      plan.push({
        version: release.runtime.version,
        rid: file.rid,
        url: file.url,
      });
    }
  }

  plan.sort((left, right) => {
    const versionCompare = left.version.localeCompare(right.version);
    if (versionCompare !== 0) {
      return versionCompare;
    }
    return left.rid.localeCompare(right.rid);
  });

  return plan;
}

export function mergeDotnetSharedFrameworkHashEntries(
  entries: PendingDotnetSharedFrameworkHashEntry[],
): Record<string, DotnetSharedFrameworkBinaryInfo> {
  const merged: Record<string, DotnetSharedFrameworkBinaryInfo> = {};

  for (const entry of entries) {
    const existing = merged[entry.hash];
    if (!existing) {
      merged[entry.hash] = {
        version: entry.version,
        binary: entry.binary,
        rids: [entry.rid],
        sources: [entry.source],
      };
      continue;
    }

    if (existing.version !== entry.version) {
      throw new Error(
        `Hash ${entry.hash} maps to conflicting versions ${existing.version} and ${entry.version}`,
      );
    }

    if (existing.binary !== entry.binary) {
      throw new Error(
        `Hash ${entry.hash} maps to conflicting binaries ${existing.binary} and ${entry.binary}`,
      );
    }

    existing.rids.push(entry.rid);
    existing.sources.push(entry.source);
  }

  for (const hash of Object.keys(merged)) {
    const entry = merged[hash];
    entry.rids = [...new Set(entry.rids)].sort();
    entry.sources = [...new Set(entry.sources)].sort();
  }

  return merged;
}

export function serializeDotnetSharedFrameworkHashesModule(
  entries: Record<string, DotnetSharedFrameworkBinaryInfo>,
  options: {
    generatedAt: string;
    generatorCommand: string;
  },
): string {
  const sortedHashes = Object.keys(entries).sort();
  const lines: string[] = [
    `// Generated by ${options.generatorCommand}`,
    `// on ${options.generatedAt}. Do not edit by hand.`,
    "",
    "export interface DotnetSharedFrameworkBinaryInfo {",
    "  version: string;",
    "  binary: string;",
    "  rids: string[];",
    "  sources: string[];",
    "}",
    "",
    "export const dotnetSharedFrameworkHashes: Record<",
    "  string,",
    "  DotnetSharedFrameworkBinaryInfo",
    "> = {",
  ];

  for (const hash of sortedHashes) {
    const entry = entries[hash];
    lines.push(`  "${hash}": {`);
    lines.push(`    version: "${entry.version}",`);
    lines.push(`    binary: "${entry.binary}",`);
    lines.push(
      `    rids: [${entry.rids.map((rid) => `"${rid}"`).join(", ")}],`,
    );
    lines.push("    sources: [");
    for (const source of entry.sources) {
      lines.push(`      "${source}",`);
    }
    lines.push("    ],");
    lines.push("  },");
  }

  lines.push("};");
  lines.push("");
  lines.push("export function lookupDotnetSharedFrameworkVersion(");
  lines.push("  hash: string,");
  lines.push("): string | undefined {");
  lines.push("  return dotnetSharedFrameworkHashes[hash]?.version;");
  lines.push("}");
  lines.push("");

  return prettier.format(lines.join("\n"), {
    parser: "typescript",
    trailingComma: "all",
    arrowParens: "always",
  });
}

async function fetchReleasesJson(channel: string): Promise<DotnetReleasesJson> {
  const url = `${DOTNET_RELEASES_METADATA_BASE}/${channel}/releases.json`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status}`);
  }
  return (await response.json()) as DotnetReleasesJson;
}

async function downloadRuntimeArchive(url: string): Promise<Readable> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to download ${url}: ${response.status}`);
  }
  if (!response.body) {
    throw new Error(`Download response for ${url} had no body`);
  }

  return Readable.fromWeb(response.body as import("stream/web").ReadableStream);
}

async function hashKeyBinariesFromRuntimeArchive(
  archiveStream: Readable,
  version: string,
  rid: string,
  source: string,
): Promise<PendingDotnetSharedFrameworkHashEntry[]> {
  const entries: PendingDotnetSharedFrameworkHashEntry[] = [];
  const versionPrefix = `${DOTNET_SHARED_FRAMEWORK_PATH}${version}/`;

  return new Promise((resolve, reject) => {
    const extractor = extract();

    extractor.on("entry", (header, stream, next) => {
      if (header.type !== "file") {
        stream.resume();
        next();
        return;
      }

      const normalizedPath = header.name.replace(/\\/g, "/");
      if (!normalizedPath.startsWith(versionPrefix)) {
        stream.resume();
        next();
        return;
      }

      const basename = normalizedPath.split("/").pop();
      if (!basename || !KEY_BINARY_NAMES_SET.has(basename)) {
        stream.resume();
        next();
        return;
      }

      streamToSha256(stream)
        .then((hash) => {
          entries.push({
            hash,
            version,
            binary: basename,
            rid,
            source,
          });
          next();
        })
        .catch(reject);
    });

    extractor.on("finish", () => resolve(entries));
    extractor.on("error", reject);

    archiveStream.pipe(gunzip()).pipe(extractor);
  });
}

function parseArgs(argv: string[]): {
  channels: string[];
  versions: string[];
  rids: string[];
  outputPath: string;
} {
  const channels: string[] = [];
  const versions: string[] = [];
  const rids: string[] = [];
  let outputPath =
    "lib/inputs/binaries/static/dotnet-shared-framework-hashes.ts";

  for (let index = 2; index < argv.length; index++) {
    const arg = argv[index];
    switch (arg) {
      case "--channel":
        channels.push(argv[++index]);
        break;
      case "--version":
        versions.push(argv[++index]);
        break;
      case "--rid":
        rids.push(argv[++index]);
        break;
      case "--output":
        outputPath = argv[++index];
        break;
      default:
        throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return {
    channels: channels.length > 0 ? channels : DEFAULT_CHANNELS,
    versions,
    rids: rids.length > 0 ? rids : DEFAULT_RIDS,
    outputPath,
  };
}

async function resolveRequestedVersions(
  channels: string[],
  explicitVersions: string[],
): Promise<string[]> {
  if (explicitVersions.length > 0) {
    return explicitVersions;
  }

  const versions: string[] = [];
  for (const channel of channels) {
    const releasesJson = await fetchReleasesJson(channel);
    versions.push(releasesJson["latest-release"]);
  }

  return [...new Set(versions)].sort();
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv);
  const requestedVersions = await resolveRequestedVersions(
    args.channels,
    args.versions,
  );

  const downloadPlan: DownloadPlanEntry[] = [];
  for (const channel of args.channels) {
    const releasesJson = await fetchReleasesJson(channel);
    downloadPlan.push(
      ...buildDownloadPlan(releasesJson, requestedVersions, args.rids),
    );
  }

  if (downloadPlan.length === 0) {
    throw new Error("No runtime archives matched the requested versions/RIDs");
  }

  const pendingEntries: PendingDotnetSharedFrameworkHashEntry[] = [];
  for (const planEntry of downloadPlan) {
    const archiveStream = await downloadRuntimeArchive(planEntry.url);
    pendingEntries.push(
      ...(await hashKeyBinariesFromRuntimeArchive(
        archiveStream,
        planEntry.version,
        planEntry.rid,
        planEntry.url,
      )),
    );
  }

  const mergedEntries = mergeDotnetSharedFrameworkHashEntries(pendingEntries);
  const generatorCommand = `npx ts-node scripts/update-dotnet-key-binary-hashes.ts${process.argv
    .slice(2)
    .map((arg) => ` ${arg}`)
    .join("")}`;
  const moduleSource = serializeDotnetSharedFrameworkHashesModule(mergedEntries, {
    generatedAt: new Date().toISOString().slice(0, 10),
    generatorCommand,
  });

  await new Promise<void>((resolve, reject) => {
    const outputStream = createWriteStream(args.outputPath);
    outputStream.on("error", reject);
    outputStream.on("finish", () => resolve());
    outputStream.write(moduleSource);
    outputStream.end();
  });

  console.log(
    `Wrote ${Object.keys(mergedEntries).length} entries to ${args.outputPath}`,
  );
}

if (require.main === module) {
  main()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}
