import { createHash } from "crypto";
import * as prettier from "prettier";
import { Readable } from "stream";
import * as tar from "tar-stream";
import { gzipSync } from "zlib";

import { streamToBuffer } from "../../lib/stream-utils";
import {
  buildDownloadPlan,
  DotnetReleasesJson,
  hashKeyBinariesFromRuntimeArchive,
  mergeDotnetSharedFrameworkHashEntries,
  PendingDotnetSharedFrameworkHashEntry,
  serializeDotnetSharedFrameworkHashesModule,
} from "../../scripts/update-dotnet-key-binary-hashes";

function sha256(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

interface FixtureTarEntry {
  name: string;
  type?: "file" | "directory" | "symlink";
  content?: string;
  linkname?: string;
}

async function buildGzippedTarArchive(
  entries: FixtureTarEntry[],
): Promise<Readable> {
  const pack = tar.pack();
  for (const entry of entries) {
    if (entry.type === "directory") {
      pack.entry({ name: entry.name, type: "directory" });
    } else if (entry.type === "symlink") {
      pack.entry({
        name: entry.name,
        type: "symlink",
        linkname: entry.linkname,
      });
    } else {
      pack.entry({ name: entry.name, type: "file" }, entry.content ?? "");
    }
  }
  pack.finalize();

  const tarBuffer = await streamToBuffer(pack);
  return Readable.from([gzipSync(tarBuffer)]);
}

const SAMPLE_RELEASES_JSON: DotnetReleasesJson = {
  "channel-version": "8.0",
  "latest-release": "8.0.30",
  releases: [
    {
      "release-version": "8.0.30",
      runtime: {
        version: "8.0.30",
        files: [
          {
            name: "dotnet-runtime-linux-x64.tar.gz",
            rid: "linux-x64",
            url: "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-x64.tar.gz",
            hash: "abc",
          },
          {
            name: "dotnet-runtime-linux-arm64.tar.gz",
            rid: "linux-arm64",
            url: "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-arm64.tar.gz",
            hash: "def",
          },
          {
            name: "dotnet-runtime-linux-musl-x64.tar.gz",
            rid: "linux-musl-x64",
            url: "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-musl-x64.tar.gz",
            hash: "ghi",
          },
          {
            name: "dotnet-runtime-win-x64.zip",
            rid: "win-x64",
            url: "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-win-x64.zip",
            hash: "jkl",
          },
        ],
      },
    },
    {
      "release-version": "8.0.29",
      runtime: {
        version: "8.0.29",
        files: [
          {
            name: "dotnet-runtime-linux-x64.tar.gz",
            rid: "linux-x64",
            url: "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.29/dotnet-runtime-8.0.29-linux-x64.tar.gz",
            hash: "mno",
          },
        ],
      },
    },
  ],
};

describe("dotnet key binary hashes generator helpers", () => {
  it("builds a download plan from releases.json for requested versions and RIDs", () => {
    expect(
      buildDownloadPlan(SAMPLE_RELEASES_JSON, ["8.0.30"], ["linux-x64", "linux-arm64"]),
    ).toEqual([
      {
        version: "8.0.30",
        rid: "linux-arm64",
        url: "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-arm64.tar.gz",
      },
      {
        version: "8.0.30",
        rid: "linux-x64",
        url: "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-x64.tar.gz",
      },
    ]);
  });

  it("serializes entries into prettier-clean TypeScript table source", () => {
    const serialized = serializeDotnetSharedFrameworkHashesModule(
      {
        abc123def4567890abc123def4567890abc123def4567890abc123def4567890: {
          version: "8.0.30",
          binary: "libcoreclr.so",
          rids: ["linux-arm64", "linux-x64"],
          sources: [
            "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-arm64.tar.gz",
            "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-x64.tar.gz",
          ],
        },
      },
      {
        generatedAt: "2026-09-02",
        generatorCommand:
          "npx ts-node scripts/update-dotnet-key-binary-hashes.ts",
      },
    );

    expect(serialized).toBe(
      [
        "// Generated by npx ts-node scripts/update-dotnet-key-binary-hashes.ts",
        "// on 2026-09-02. Do not edit by hand.",
        "",
        "export interface DotnetSharedFrameworkBinaryInfo {",
        "  version: string;",
        "  binary: string;",
        "  rids: string[];",
        "  sources: string[];",
        "}",
        "",
        "export const dotnetSharedFrameworkHashes: Record<",
        "  string,",
        "  DotnetSharedFrameworkBinaryInfo",
        "> = {",
        '  abc123def4567890abc123def4567890abc123def4567890abc123def4567890: {',
        '    version: "8.0.30",',
        '    binary: "libcoreclr.so",',
        '    rids: ["linux-arm64", "linux-x64"],',
        "    sources: [",
        '      "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-arm64.tar.gz",',
        '      "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-x64.tar.gz",',
        "    ],",
        "  },",
        "};",
        "",
        "export function lookupDotnetSharedFrameworkVersion(",
        "  hash: string,",
        "): string | undefined {",
        "  return dotnetSharedFrameworkHashes[hash]?.version;",
        "}",
        "",
      ].join("\n"),
    );

    expect(
      prettier.format(serialized, {
        parser: "typescript",
        trailingComma: "all",
        arrowParens: "always",
      }),
    ).toBe(serialized);
  });

  it("merges same-version same-binary hits across RIDs deterministically", () => {
    const sharedHash =
      "111122223333444455556666777788889999aaaabbbbccccddddeeeeffff";
    const linuxX64Source =
      "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-x64.tar.gz";
    const linuxMuslX64Source =
      "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-musl-x64.tar.gz";

    const firstEntry: PendingDotnetSharedFrameworkHashEntry = {
      hash: sharedHash,
      version: "8.0.30",
      binary: "System.Private.CoreLib.dll",
      rid: "linux-x64",
      source: linuxX64Source,
    };
    const secondEntry: PendingDotnetSharedFrameworkHashEntry = {
      hash: sharedHash,
      version: "8.0.30",
      binary: "System.Private.CoreLib.dll",
      rid: "linux-musl-x64",
      source: linuxMuslX64Source,
    };

    const expected = {
      [sharedHash]: {
        version: "8.0.30",
        binary: "System.Private.CoreLib.dll",
        rids: ["linux-musl-x64", "linux-x64"],
        sources: [linuxMuslX64Source, linuxX64Source],
      },
    };

    expect(
      mergeDotnetSharedFrameworkHashEntries([firstEntry, secondEntry]),
    ).toEqual(expected);
    expect(
      mergeDotnetSharedFrameworkHashEntries([secondEntry, firstEntry]),
    ).toEqual(expected);
  });

  it("throws when one hash maps to conflicting versions or binary names", () => {
    const sharedHash =
      "aaaabbbbccccddddeeeeffff11112222333344445555666677778888";

    expect(() =>
      mergeDotnetSharedFrameworkHashEntries([
        {
          hash: sharedHash,
          version: "8.0.30",
          binary: "libcoreclr.so",
          rid: "linux-x64",
          source:
            "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-x64.tar.gz",
        },
        {
          hash: sharedHash,
          version: "8.0.29",
          binary: "libcoreclr.so",
          rid: "linux-arm64",
          source:
            "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.29/dotnet-runtime-8.0.29-linux-arm64.tar.gz",
        },
      ]),
    ).toThrow(/conflicting versions 8\.0\.30 and 8\.0\.29/);

    expect(() =>
      mergeDotnetSharedFrameworkHashEntries([
        {
          hash: sharedHash,
          version: "8.0.30",
          binary: "libcoreclr.so",
          rid: "linux-x64",
          source:
            "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-x64.tar.gz",
        },
        {
          hash: sharedHash,
          version: "8.0.30",
          binary: "System.Private.CoreLib.dll",
          rid: "linux-x64",
          source:
            "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-x64.tar.gz",
        },
      ]),
    ).toThrow(
      /conflicting binaries libcoreclr\.so and System\.Private\.CoreLib\.dll/,
    );
  });
});

describe("hashKeyBinariesFromRuntimeArchive", () => {
  const source =
    "https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.30/dotnet-runtime-8.0.30-linux-x64.tar.gz";

  it("hashes only key binaries under the requested version's shared framework path", async () => {
    const coreclrContent = "coreclr-binary-8.0.30";
    const corelibContent = "corelib-binary-8.0.30";

    const archiveStream = await buildGzippedTarArchive([
      {
        name: "shared/Microsoft.NETCore.App/8.0.30/libcoreclr.so",
        content: coreclrContent,
      },
      {
        name: "shared/Microsoft.NETCore.App/8.0.30/System.Private.CoreLib.dll",
        content: corelibContent,
      },
      {
        name: "shared/Microsoft.NETCore.App/8.0.30/System.Runtime.dll",
        content: "not-a-key-binary",
      },
      {
        name: "shared/Microsoft.NETCore.App/8.0.29/libcoreclr.so",
        content: "wrong-version",
      },
      {
        name: "shared/Microsoft.AspNetCore.App/8.0.30/libcoreclr.so",
        content: "wrong-framework",
      },
      {
        name: "shared/Microsoft.NETCore.App/8.0.30/nested/",
        type: "directory",
      },
    ]);

    const entries = await hashKeyBinariesFromRuntimeArchive(
      archiveStream,
      "8.0.30",
      "linux-x64",
      source,
    );

    expect(entries).toEqual([
      {
        hash: sha256(coreclrContent),
        version: "8.0.30",
        binary: "libcoreclr.so",
        rid: "linux-x64",
        source,
      },
      {
        hash: sha256(corelibContent),
        version: "8.0.30",
        binary: "System.Private.CoreLib.dll",
        rid: "linux-x64",
        source,
      },
    ]);
  });

  it("matches on backslash-style archive paths", async () => {
    const content = "coreclr-backslash";
    const archiveStream = await buildGzippedTarArchive([
      {
        name: "shared\\Microsoft.NETCore.App\\8.0.30\\libcoreclr.so",
        content,
      },
    ]);

    const entries = await hashKeyBinariesFromRuntimeArchive(
      archiveStream,
      "8.0.30",
      "linux-x64",
      source,
    );

    expect(entries).toEqual([
      {
        hash: sha256(content),
        version: "8.0.30",
        binary: "libcoreclr.so",
        rid: "linux-x64",
        source,
      },
    ]);
  });

  it("skips non-file entries even when their path and name match a key binary", async () => {
    const archiveStream = await buildGzippedTarArchive([
      {
        name: "shared/Microsoft.NETCore.App/8.0.30/libcoreclr.so",
        type: "symlink",
        linkname: "libcoreclr.so.real",
      },
    ]);

    const entries = await hashKeyBinariesFromRuntimeArchive(
      archiveStream,
      "8.0.30",
      "linux-x64",
      source,
    );

    expect(entries).toEqual([]);
  });

  it("returns no entries when nothing matches the requested version", async () => {
    const archiveStream = await buildGzippedTarArchive([
      {
        name: "shared/Microsoft.NETCore.App/8.0.29/libcoreclr.so",
        content: "wrong-version",
      },
    ]);

    const entries = await hashKeyBinariesFromRuntimeArchive(
      archiveStream,
      "8.0.30",
      "linux-x64",
      source,
    );

    expect(entries).toEqual([]);
  });
});
